vich_uploader:
    db_driver: orm

    mappings:
        products_images:
            uri_prefix: /images/pictures
            upload_destination: '%kernel.project_dir%/public/images/pictures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true


